### ISSUE TITLE
Cannot redefine event class `bend-span-event'

### ISSUE THREAD

**Issue by oidavoda** [nwhetsell/lilypond-bending-additions#1]
I tried to compile the snippet given on https://github.com/nwhetsell/lilypond-bending-additions with LilyPond 2.23.4 and get the following error message:

```
fatal error: Cannot redefine event class `bend-span-event'

Module lyluatex Warning: The score doesn't contain any music:
(lyluatex)               this will probably cause bad output. on input line 98
/usr/share/texlive/texmf-dist/tex/latex/base/ltluatex.lua:109: 
Module lyluatex Error: 
(lyluatex)             LilyPond failed to compile the score.
(lyluatex)             Please check the log file
(lyluatex)             and the generated LilyPond code in
(lyluatex)             tmp-ly/d619eed0af0aad779d2d7ac6db64f5fb.log
(lyluatex)             tmp-ly/d619eed0af0aad779d2d7ac6db64f5fb.ly
(lyluatex)             
(lyluatex)             on input line 98

stack traceback:
	[C]: in function 'error'
	/usr/share/texlive/texmf-dist/tex/latex/base/ltluatex.lua:109: in function </u
sr/share/texlive/texmf-dist/tex/latex/base/ltluatex.lua:108>
	(...tail calls...)
	./lyluatex.lua:550: in method 'check_compilation'
	./lyluatex.lua:1194: in method 'write_latex'
	./lyluatex.lua:1118: in method 'process'
	[\directlua]:1: in main chunk.
\ly@compilescore ...directlua {ly.score:process()}
```

**Comment by nwhetsell** [comment]
If you want to use these LilyPond functions with https://github.com/nwhetsell/lilypond-bend-spanner (which is the real source of the problem), you’ll need to downgrade to the latest stable version of LilyPond ([2.22](https://lilypond.org/download.html)).

However, unless you really need the bent grace notes these functions provide, you’ll probably be better off not using these functions at all and using the [string bending interface that was added directly to LilyPond 2.23](https://lilypond.org/doc/v2.23/Documentation/notation/common-notation-for-fretted-strings#index-string-bending_002c-in-tablature-notation):

```sh
lilypond --output=bending --svg - <<EOS
\version "2.23.4"
\paper {
  page-breaking = #ly:one-line-auto-height-breaking
  top-margin = 0
  left-margin = 0
  right-margin = 0
  oddFooterMarkup= ##f
}
\pointAndClickOff
music = \relative {
  \grace c'8 \^ d4
  \grace c8\preBend \^ \afterGrace d4 \^ c8
}
\score {
  <<
    \new Staff { \clef "treble_8" \music }
    \new TabStaff \music
  >>
}
EOS
```

![bending-additions](https://user-images.githubusercontent.com/14102861/206290369-10ea3581-4a6c-4ab1-8437-8179ef523a99.svg)

If you really need these bent grace notes, you can get them in LilyPond 2.23, but you need to define `startBend` and `stopBend` variables as workarounds (I’m planning to update this when LilyPond 2.24 is released):

```sh
lilypond --output=bending-additions --svg - <<EOS
\version "2.23.4"
\include "bending-additions.ily"
startBend = \^
stopBend = {}
\paper {
  page-breaking = #ly:one-line-auto-height-breaking
  top-margin = 0
  left-margin = 0
  right-margin = 0
  oddFooterMarkup= ##f
}
\pointAndClickOff
music = \relative {
  \grace-startBend c'8 d4
  \bent-grace c8\preBend \^ \afterGrace d4 \^ { \afterGrace-stopBend c8 }
}
\score {
  <<
    \new Staff { \clef "treble_8" \music }
    \new TabStaff \music
  >>
}
EOS
```

![bending-additions](https://user-images.githubusercontent.com/14102861/206291677-e9c53882-e804-4af7-9d1e-3546aa13fc65.svg)
